GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "How to love",
  "author": "Dansiro",
  "url": "google.com.vn",
  "likes": 10
}